# -*- coding: utf-8 -*-
"""
Created on Fri Jun  7 10:12:21 2024

@author: sajit
"""

import streamlit as st
from PIL import Image
import pandas as pd

def show_home():
    st.header("Insurance Claim Modelling System", divider='red')
    st.markdown("\n")
    st.write(
        """
       Dive into the world of Insurance Claim Modelling with this demo that explores the data used, the data preparation process, the machine learning algorithms employed, and the valuable insights it generates!
        
        """
    )
    
    st.markdown("\n")
    # Text to display
    text = "&nbsp;Model Definition : Predict the likelihood of claims within the first 3 years of policy initiation.&nbsp;"
    
    # Define HTML with inline CSS (replace with desired color)
    html_string = f"<b style='background-color:#E9ECE4; color:#333; padding: 20px;padding-right: 30px; text-align: center;'>{text}</b>"
    st.markdown("\n")
    st.markdown("\n")
    # Display the HTML with unsafe_allow_html (use with caution)
    st.markdown(html_string, unsafe_allow_html=True)
    st.markdown("\n")
    st.markdown("\n")
        
    # Display the HTML content
    st.markdown("<h6 style='text-align: center; color: black;'>&ensp; &ensp; <u>Insurance Claim Modelling System</u></h6>", unsafe_allow_html=True)
    
    # Define border width and color (adjust values as needed)
    border_width = 10
    border_color = (220, 220, 220)  # Light gray border
    image = Image.open("images/modelsummary.jpg")
    # Display the selected image
    bordered_image = Image.new("RGB", (image.width + 2 * border_width, 
                                image.height + 2 * border_width), border_color)
    # Paste the original image onto the new image with border2
    bordered_image.paste(image, (border_width, border_width))
    st.image(image)
    
    st.markdown("\n")
            
    st.markdown("**Types of input :** ")
    # Create a sample DataFrame (replace with your data)
    data = {
        'Profile Data': ['Age, Gender, Occupation etc.'],
        'Medical Data': ['Previous and current medical history'],
        'Insurance Policy Data': ['Policy no, Annual premium, Agent info etc.']
    }
    df = pd.DataFrame(data)
    
    # Display the DataFrame using st.dataframe
    st.dataframe(df,use_container_width=True,hide_index=True)
  
 
    st.markdown(" **Outputs generated by the model :** ")
    data = {
        'Prediction Probability': ['Probability of policy converting into a claim'],
        'Probability Bucket': ['Probability divided into quantiles'],
        'Probability Category': ['High, Medium, Low etc.']
    }
    df = pd.DataFrame(data)
    
    # Display the DataFrame using st.dataframe
    st.dataframe(df,use_container_width=True,hide_index=True)        
            
        
        